### ISSUE TITLE
Node red addon crashes - suspect Harmony node but cannot remove that node

### ISSUE THREAD

**Issue by gsbrown** [notoriousbdg/hassio-addons#15]
Here is the log. The addon seems to crash mostly when I am in there tinkering. This is the Harmony node that I installed: https://flows.nodered.org/node/node-red-contrib-harmony
```17 Nov 14:06:02 - [red] Uncaught Exception:
17 Nov 14:06:02 - Error: MAX_CLIENTS=6
    at Connection.onStanza (/data/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/data/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:96:13)
    at StreamParser.emit (events.js:188:7)
    at SaxLtx.<anonymous> (/data/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:96:13)
    at SaxLtx.emit (events.js:188:7)
    at SaxLtx._handleTagOpening (/data/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/data/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/data/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
npm info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
npm ERR! Linux 4.4.50
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.0 start script 'node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-docker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-docker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-red-docker
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/node-red/npm-debug.log`

**Comment by notoriousbdg** [comment]
You mentioned on the forums that you've resolved this so I'm closing this.
