### ISSUE TITLE
Unable to install HA-Bridge

### ISSUE THREAD

**Issue by cbrherms** [notoriousbdg/hassio-addons#16]
Added repository, upon clicking on HA-Bridge and then install, button spins a sec then goes red and does nothing.

Supervisord log:

```
17-11-20 07:37:43 INFO (SyncWorker_12) [hassio.dock.addon] Start build 27e642c6/armhf-addon-ha-bridge:4.5.6p3
17-11-20 07:37:43 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 323, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 474, in install
    if not await self.docker.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 219, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 232, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: Please provide a source image with `from` prior to commit
```

**Comment by cbrherms** [comment]
Issue found, host needed updating (assuming docker version issue)
