### ISSUE TITLE
Can't install this addon

### ISSUE THREAD

**Issue by mauriciobonani** [notoriousbdg/hassio-addons#17]
I'm seeing these error messages in the log when trying to install this addon. My hass.io is running on Ubuntu Server 17.10.

17-11-24 21:46:21 INFO (SyncWorker_3) [hassio.dock.addon] Start build 27e642c6/amd64-addon-nodered:0.1.4
17-11-24 21:46:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 323, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 474, in install
    if not await self.docker.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 219, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 232, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: Please provide a source image with `from` prior to commit

How can I fix this problem?

Thanks.

**Comment by notoriousbdg** [comment]
Looks like you're running an old version of Docker.

**Comment by mauriciobonani** [comment]
You are right, I was using the docker.io package.
