### ISSUE TITLE
Can't install any modules

### ISSUE THREAD

**Issue by kolossboss** [notoriousbdg/hassio-addons#21]
Hi,
I can't install any modules via "manage palette"
I have no "bad" network connection neither using a proxy.

I tried reinstalling with no luck. Other Addons are working without issues.
I see this in the debug log. Please help.

This is strange in the log: `39 error network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443`
Why are there two domains and with port :443?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '--save-prefix="~"',
1 verbose cli   '--production',
1 verbose cli   'node-red-contrib-home-assistant@0.2.0' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData node-red-contrib-home-assistant@0.2.0
8 silly fetchNamedPackageData node-red-contrib-home-assistant
9 silly mapToRegistry name node-red-contrib-home-assistant
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'node-red-contrib-home-assistant',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'node-red-contrib-home-assistant',
12 silly mapToRegistry   name: 'node-red-contrib-home-assistant',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/node-red-contrib-home-assistant
14 verbose request uri https://registry.npmjs.org/node-red-contrib-home-assistant
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:16:18 PM
17 verbose request id c875340b2bd35dc6
18 http request GET https://registry.npmjs.org/node-red-contrib-home-assistant
19 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
20 info attempt registry request try #2 at 10:16:48 PM
21 http request GET https://registry.npmjs.org/node-red-contrib-home-assistant
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
23 info attempt registry request try #3 at 10:18:08 PM
24 http request GET https://registry.npmjs.org/node-red-contrib-home-assistant
25 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for node-red-contrib-home-assistant@0.2.0 { Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'ENOTFOUND',
25 silly fetchPackageMetaData   errno: 'ENOTFOUND',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
30 verbose stack     at errnoException (dns.js:28:10)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
31 verbose cwd /share/node-red
32 error Linux 4.4.50
33 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-prefix=\"~\"" "--production" "node-red-contrib-home-assistant@0.2.0"
34 error node v6.11.0
35 error npm  v3.10.10
36 error code ENOTFOUND
37 error errno ENOTFOUND
38 error syscall getaddrinfo
39 error network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
40 error network This is most likely not a problem with npm itself
40 error network and is related to network connectivity.
40 error network In most cases you are behind a proxy or have bad network settings.
40 error network
40 error network If you are behind a proxy, please make sure that the
40 error network 'proxy' config is set properly.  See: 'npm help config'
41 verbose exit [ 1, true ]
```

**Comment by notoriousbdg** [comment]
That looks like you've got DNS issues.  Make sure you've got DNS setup correctly on your hassio host.

**Comment by kolossboss** [comment]
hm. Everything else works fine on hassio.
The only thing I did, was setting up Pi-Hole on the same raspberry, and adding the Pi-Hole DNS to my DHCP DNS Server.

**Comment by kolossboss** [comment]
Ok strange. Setting up the the DHCP DNS to the Standard setting and now I works. No idea why its not working with Pi-Hole as DNS Server.
I try to find out why. Thx for helping

**Comment by notoriousbdg** [comment]
I don't use Pi-Hole, so I'm not sure how it works.  Based on your symptoms, it sounds like forwarding either isn't configured or isn't working.  Ideally, it should be forwarding DNS requests instead of using host's DNS client for resolution.

**Comment by kolossboss** [comment]
Yes,
I think its a problem with the pi-hole addon itself. I set a static DNS (not pi-hole) to the ResinOS and the problems are gone. 
And if a use pi-hole on an separate raspberry, there are also no problems with node red.
Thanks for helping
