### ISSUE TITLE
join

### ISSUE THREAD

**Issue by rpeders** [notoriousbdg/hassio-addons#32]
installed join from palette (http://www.notenoughtech.com/tasker/tasker-tutorial/make-use-of-join-custom-commands/)
and did something wrong.. nodered charshes : https://pastebin.com/edit/Prn4j8XE
cannot start flows due to missing things if i delete tht dir.
if i reinstall that from palette nodered chrashes again and i have to delete that dir to start..
how can i fix this?

**Comment by notoriousbdg** [comment]
I can't access your log because it requires authentication.  Either paste the log here or provide an accessible link.  Join looks to be a paid service, so you might be better off going through their official support channel first since you've paid for it.  I found their github repo at https://github.com/joaomgcd/node-red-contrib-join-joaoapps.

**Comment by rpeders** [comment]
23 Mar 15:17:43 - [info] Waiting for missing types to be registered:
23 Mar 15:17:43 - [info]  - join-config
23 Mar 15:17:43 - [info]  - join-server
23 Mar 15:17:43 - [info]  - join-receive-message
23 Mar 15:20:39 - [info] Stopping flows
23 Mar 15:20:39 - [info] Stopped flows
23 Mar 15:20:39 - [info] Waiting for missing types to be registered:
23 Mar 15:20:39 - [info]  - join-config
23 Mar 15:20:39 - [info]  - join-server
23 Mar 15:31:33 - [info] Installing module: node-red-contrib-join-joaoapps, version: 1.0.6
23 Mar 15:32:37 - [info] Installed module: node-red-contrib-join-joaoapps
23 Mar 15:32:37 - [info] Missing type registered: join-config
23 Mar 15:32:37 - [info] Missing type registered: join-server
23 Mar 15:32:37 - [info] Starting flows
23 Mar 15:32:37 - [info] [join-server:2173479f.de7b78] Starting server on port 1880...
23 Mar 15:32:38 - [info] Started flows
23 Mar 15:32:38 - [red] Uncaught Exception:
23 Mar 15:32:38 - Error: listen EADDRINUSE :::1880
    at Server.setupListenHandle [as _listen2] (net.js:1342:14)
    at listenInCluster (net.js:1383:12)
    at Server.listen (net.js:1471:7)
    at new JoinServerNode (/share/node-red/node_modules/node-red-contrib-join-joaoapps/join-server.js:59:7)
    at createNode (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:305:18)
    at Flow.start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/Flow.js:67:31)
    at start (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:307:29)
    at EventEmitter.<anonymous> (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/flows/index.js:62:25)
    at EventEmitter.emit (events.js:180:13)
    at Object.registerNodeConstructor [as registerType] (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/registry/registry.js:418:12)
    at Object.registerType (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/index.js:64:14)
    at Object.red.nodes.registerType (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/registry/loader.js:77:23)
    at module.exports (/share/node-red/node_modules/node-red-contrib-join-joaoapps/join-server.js:113:15)
    at loadNodeSet (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/registry/loader.js:304:27)
    at /usr/src/node-red/node_modules/node-red/red/runtime/nodes/registry/loader.js:344:27
    at Array.forEach (<anonymous>)
    at loadNodeSetList (/usr/src/node-red/node_modules/node-red/red/runtime/nodes/registry/loader.js:342:11)
    at /usr/src/node-red/node_modules/node-red/red/runtime/nodes/registry/loader.js:165:16
    at tryCatchReject (/usr/src/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/src/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/src/node-red/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/src/node-red/node_modules/when/lib/makePromise.js:483:13)
npm info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/share/node-red"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-23T14_32_38_898Z-debug.log

**Comment by notoriousbdg** [comment]
Looks like it's failing because join-server is attempting to listen on port 1880, but that's the port used by Node-RED.  Check to see if you can move join-server to a unique port.

**Comment by rpeders** [comment]
im trying to get rid of join but the more i try the more mess i make... lol seems like i have to start over and making all my flows from scratch.. :( 
Tried removing join from package.json and package-lock.jsoncand now i cant access because of encryption... my last hope is if there is a way to copy my flows somehow im guessing??

**Comment by rpeders** [comment]
im guess i have to start over.. any chance of getting my flows out first without starting nodered '(wont start)
the flows.json.backup, flows_cred.json.backup, flows.json and flows_cred.json files, would they contain the info i need to recreate my flows? or are they encrypted?

**Comment by rpeders** [comment]
I managed to get it all back.. uninstalled nodered, deleted nodered folder, and copied all the text from flows json to clipboard. That imported all my flows. Then i added missing "palettetes" one by one util there was only join left. Then i found out how to delete missing components without installing join node, and now it all works. thanx for your assistanse.. loving nodered
