### ISSUE TITLE
Node-red crashes after a while

### ISSUE THREAD

**Issue by cbrherms** [notoriousbdg/hassio-addons#39]
Currently have the add-on served via a reverse proxy with SSL termination. Seems to be running fine from a serving point of view and can connect to my HA API, but it will crash after 10 mins or so. Log is as follows:

```
[INFO] Disabling SSL
[INFO] Updating IDE Users
[INFO] Adding IDE User admin
[INFO] Disabling HTTP Node Authentication
[INFO] Disabling Projects
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v10.0.0
npm info lifecycle node-red-docker@1.0.0~prestart: node-red-docker@1.0.0
npm info lifecycle node-red-docker@1.0.0~start: node-red-docker@1.0.0
> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/share/node-red"
15 May 01:45:44 - [info] 
Welcome to Node-RED
===================
15 May 01:45:44 - [info] Node-RED version: v0.18.5
15 May 01:45:44 - [info] Node.js  version: v10.0.0
15 May 01:45:44 - [info] Linux 4.4.50 arm LE
15 May 01:45:46 - [info] Loading palette nodes
15 May 01:45:53 - [info] Settings file  : /share/node-red/settings.js
15 May 01:45:53 - [info] User directory : /share/node-red
15 May 01:45:53 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
15 May 01:45:53 - [info] Flows file     : /share/node-red/flows.json
15 May 01:45:53 - [warn] 
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
15 May 01:45:53 - [info] Starting flows
15 May 01:45:54 - [info] Started flows
15 May 01:45:54 - [info] Server now running at http://127.0.0.1:1880/
15 May 01:58:40 - [red] Uncaught Exception:
15 May 01:58:40 - TypeError: flatten.depth is not a function
    at /share/node-red/node_modules/bonjour/lib/mdns-server.js:54:17
    at Array.forEach (<anonymous>)
    at Server._respondToQuery (/share/node-red/node_modules/bonjour/lib/mdns-server.js:48:19)
    at EventEmitter.emit (events.js:182:13)
    at Socket.<anonymous> (/share/node-red/node_modules/multicast-dns/index.js:48:40)
    at Socket.emit (events.js:182:13)
    at UDP.onMessage [as onmessage] (dgram.js:670:8)
npm info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/share/node-red"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-15T00_58_40_753Z-debug.log
```

Any thoughts anyone? I only had the one test flow in at the time. Simple input to a HA service call

**Comment by notoriousbdg** [comment]
That doesn't look related to the addon.  https://github.com/webpack/webpack-dev-server/issues/989 looks similar.
