### ISSUE TITLE
Node red Crashes

### ISSUE THREAD

**Issue by filoor** [notoriousbdg/hassio-addons#43]
Hi
It crashes every time

log:
14 Jun 20:38:29 - [info] Started flows
```
Disconnected from Harmony Hub: Error: Timed out after 50000 ms
Disconnected from Harmony Hub: Error: Timed out after 50000 ms
Disconnected from Harmony Hub: Error: Timed out after 50000 ms
Disconnected from Harmony Hub: Error: Timed out after 50000 ms
14 Jun 20:38:54 - [red] Uncaught Exception:
14 Jun 20:38:54 - Error: MAX_CLIENTS=6
    at Connection.onStanza (/share/node-red/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/share/node-red/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:115:13)
    at StreamParser.emit (events.js:210:7)
    at SaxLtx.<anonymous> (/share/node-red/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:115:13)
    at SaxLtx.emit (events.js:210:7)
    at SaxLtx._handleTagOpening (/share/node-red/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/share/node-red/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/share/node-red/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
npm info lifecycle node-red-docker@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/share/node-red"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-14T18_38_54_383Z-debug.log
```

**Comment by notoriousbdg** [comment]
Looks like one of the issues mentioned at https://github.com/KraigM/homebridge-harmonyhub/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+MAX_CLIENTS%3D6.

**Comment by filoor** [comment]
I just did a try with the othe node-red the default one for hass.io
and it looks like it restarts node red automatically

Can you do something like that  
```

Disconnected from Harmony Hub: Error: Timed out after 50000 ms
Disconnected from Harmony Hub: Error: Timed out after 50000 ms
14 Jun 22:07:23 - [red] Uncaught Exception:
14 Jun 22:07:23 - Error: MAX_CLIENTS=6
    at Connection.onStanza (/config/node-red/node_modules/node-xmpp-core/lib/Connection.js:355:17)
    at StreamParser.<anonymous> (/config/node-red/node_modules/node-xmpp-core/lib/Connection.js:226:10)
    at emitOne (events.js:116:13)
    at StreamParser.emit (events.js:211:7)
    at SaxLtx.<anonymous> (/config/node-red/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
    at emitOne (events.js:116:13)
    at SaxLtx.emit (events.js:211:7)
    at SaxLtx._handleTagOpening (/config/node-red/node_modules/ltx/lib/parsers/ltx.js:31:18)
    at SaxLtx.write (/config/node-red/node_modules/ltx/lib/parsers/ltx.js:105:26)
    at StreamParser.write (/config/node-red/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hassio-addon-node-red@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-14T20_07_23_422Z-debug.log
> hassio-addon-node-red@1.0.0 start /opt
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
14 Jun 22:07:29 - [info] 
Welcome to Node-RED
```

**Comment by notoriousbdg** [comment]
I suspect that you need to remove the package that's causing node-red to crash.
